language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_EMULATOR_API_LEVEL=23
    - ANDROID_BUILD_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=24.0.3
    - ANDROID_ABI=default/armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10
    - MALLOC_ARENA_MAX=2
  matrix:
    - SUBPROJECT=App
    - SUBPROJECT=CMS

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_BUILD_API_LEVEL
    - android-$ANDROID_EMULATOR_API_LEVEL
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_API_LEVEL

before_install:
  - cd $SUBPROJECT

script:
  - chmod 777 ./travis.sh
  - ./travis.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
